### ISSUE TITLE
Use Static Variables and Methods

### ISSUE THREAD

**Issue by as269** [as269/IS247Proj#15]
Static variables:
Track total number of transactions or books.

Static methods:
Implement utility methods like ID validation or book search.

**Comment by abbiemn9** [comment]
public static void allBooks() {
        System.out.println("\nAll Books available:");
        for (Book book : allOfBooks) {
        System.out.println("Title: " + book.getTitle() + ", Author: " + book.getAuthor() + ", ISBN: " + book.getIsbn());
        }
        }
public static Book ISBNsearch (String ISBN){
        for(Book book:allOfBooks){
        if(book.getIsbn().equals(isbn)){
        return book;
        }
        }
        }
