### ISSUE TITLE
Create Java Docs

### ISSUE THREAD

**Issue by as269** [as269/IS247Proj#19]
**Can wait until the code is finished**

Use the following format to write a comment on the top of a class or method and explain what it does:
/**
*/

There's a sample code provided in Java Docs file, it will help with creating a Java Doc or we can use IntelliJ - > there is a built in function under tools.

**Comment by abbiemn9** [comment]
package com.library.management;

/**
 * Book in the library management system
 */
public class Book {
    /**
     * Book title
     */
    private String title;
    /**
     * Book author
     */
    private String author;
    /**
     * Book ISBN
     */
    private String ISBN;
    /**
     * Whether book is available or not
     */
    private boolean available;

    /**
     * Constructing new Book object with title, author, and ISBN
     *
     * @param title
     * @param author
     * @param ISBN
     */
    public Book(String title, String author, String ISBN) {
        this.title = title;
        this.author = author;
        this.ISBN = ISBN;
        this.available = true;
        /**
         * Book is available by default
         */

    }

    /**
     * Constructing a new Book object with the title and author.
     *
     * @param title
     * @param author
     */
    public Book(String title, String author) { // Method overloading
        this(title, author, "Unknown");
        /**
         * ISBN is unknown by default
         */
    }

    /**
     * Gets book title
     *
     * @return book title
     */
    public String getTitle() {
        return title;
    }

    /**
     * Gets author of book
     *
     * @return author
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Gets ISBN of book
     *
     * @return ISBN
     */
    public String getISBN() {
        return ISBN;
    }

    /**
     * Sets ISBN of book
     *
     * @param ISBN
     */
    public void setISBN(String ISBN) {
        this.ISBN = ISBN;
    }

    /**
     * Will check availability of book
     *
     * @return true if book is available
     */
    public boolean isAvailable() {
        return available;
    }

    /**
     * Sets if book is available
     *
     * @param available
     */
    public void setAvailable(boolean available) {
        this.available = available;
    }

    /**
     * Returns String of Book object
     *
     * @return String of Book object
     */
    @Override
    public String toString() {
        return String.format("Title: %s, Author: %s, ISBN: %s, Available: %s", title, author, ISBN, available);
    }
}

**Comment by abbiemn9** [comment]
package com.library.management;

import java.util.Date;

/**
 * Borrow Transaction of book from a library member
 */
public class BorrowTransaction extends Transaction {
    /**
     * The book that was borrowed
     */
    private final Book book;
    /**
     * Library member who borrows book
     */
    private final Member member;
    /**
     * Date of transaction
     */
    private final Date transactionDate;

    /**
     * Constructing the BorrowTransaction object with transaction ID, transaction date, the book, and the member
     *
     * @param transactionID
     * @param transactionDate
     * @param book
     * @param member
     */
    public BorrowTransaction(String transactionID, Date transactionDate, Book book, Member member) {
        super();
        this.book = book;
        this.member = member;
        this.transactionDate = transactionDate;
    }

    /**
     * Gets book that was borrowed
     *
     * @return the book that was borrowed
     */
    public Book getBook() {
        return book;
    }

    /**
     * Gets library member who borrowed the book
     *
     * @return the library member who borrowed the book
     */
    public Member getMember() {
        return member;
    }

    /**
     * Gets the date of transaction
     *
     * @return the date of transaction
     */
    public Date getTransactionDate(){
        return transactionDate;
    }

    /**
     * Processes borrow transaction
     * Sets book as borrowed
     */
    @Override
    public void process() {
        if (book.isAvailable()) {
            book.setAvailable(false);
            member.borrowBook(book);
            System.out.println("Book borrowed successfully.");
        } else {
            System.out.println("Book is not available.");
        }
    }
}

**Comment by abbiemn9** [comment]
package com.library.management;

/**
 * Interface for borrowing books
 */
public interface Borrowable {
    /**
     * Borrow book
     *
     * @param book to borrow
     */
    void borrowBook(Book book);

    /**
     * Return book
     *
     * @param book to return
     */
    void returnBook(Book book);
}

**Comment by abbiemn9** [comment]
package com.library.management;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Stack;

/**
 * Library management system for books, members, transactions, and transaction history
 */
public class Library {
    /**
     * Library book list
     */
    private ArrayList<Book> books;
    /**
     * Library member map
     */
    private Map<String, Member> members;
    /**
     * Library transaction list
     */
    private ArrayList<Transaction> transactions;
    /**
     * Library stack transaction history
     */
    private Stack<Transaction> transactionHistory;

    /**
     * Constructing library object
     * Initiallizing books, members, transactions, and transaction history
     */
    public Library() {
        books = new ArrayList<>();
        members = new HashMap<>();
        transactions = new ArrayList<>();
        transactionHistory = new Stack<>();
    }

    /**
     * Adds library book
     *
     * @param book added
     */
    public void addBook(Book book) {
        books.add(book);
    }

    /**
     * Adds library member
     *
     * @param member added
     */
    public void addMember(Member member) {
        members.put(member.getMemberID(), member);
    }

    /**
     * Finds library member by ID
     *
     * @param memberId of the member
     * @return library member object if member is found
     */
    public Member findMemberById(String memberId) {
        return members.get(memberId);
    }

    /**
     * Book borrow transaction
     *
     * @param transactionID
     * @param transactionDate
     * @param member
     * @param book
     */
    public void borrowBook(String transactionID, Date transactionDate, Member member, Book book) {
        BorrowTransaction borrowTransaction = new BorrowTransaction(transactionID, transactionDate, book, member);
        borrowTransaction.process();
        transactions.add(borrowTransaction);
        transactionHistory.push(borrowTransaction);
    }

    /**
     *
     * @param transactionID
     * @param transactionDate
     * @param member
     * @param book
     */
    public void returnBook(String transactionID, Date transactionDate, Member member, Book book) {
        ReturnTransaction returnTransaction = new ReturnTransaction(book, member);
        returnTransaction.process();
        transactions.add(returnTransaction);
        transactionHistory.push(returnTransaction);
    }

    /**
     * Searches for book by book title or ISBN
     *
     * @param query
     * @return book object if found
     */
    public Book searchBook(String query) {
        for (Book book : books) {
            if (book.getTitle().equalsIgnoreCase(query) || book.getISBN().equalsIgnoreCase(query)) {
                return book;
            }
        }
        return null;
    }

    /**
     * Displays transaction history of borrowing and returning books
     * Prints transaction details
     */
    public void displayTransactionHistory() {
        System.out.println("Transaction History:");
        for (Transaction transaction : transactionHistory) {
            if (transaction instanceof BorrowTransaction) {
                BorrowTransaction borrowTransaction = (BorrowTransaction) transaction;
                System.out.printf("Date: %s, Member: %s borrowed Book: %s\n",
                        borrowTransaction.getTransactionDate(), borrowTransaction.getMember().getName(),
                        borrowTransaction.getBook().getTitle());
            } else if (transaction instanceof ReturnTransaction) {
                ReturnTransaction returnTransaction = (ReturnTransaction) transaction;
                System.out.printf("Date: %s, Member: %s returned Book: %s\n",
                        returnTransaction.getTransactionDate(), returnTransaction.getMember().getName(),
                        returnTransaction.getBook().getTitle());
            }
        }
    }

}

**Comment by abbiemn9** [comment]
package com.library.management;

import java.util.Date;
import java.util.Scanner;

/**
 * The menu for users to use the library
 */
public class Main {
    private static Scanner scanner = new Scanner(System.in);
    private static Library library = new Library();

    /**
     * Displays the main menu
     */
    private static void displayMainMenu() {
        System.out.println("Library Management System");
        System.out.println("1. Borrow Book");
        System.out.println("2. Return Book");
        System.out.println("3. Search Book");
        System.out.println("4. Display Transaction History");
        System.out.println("5. Exit");
        System.out.print("Enter your choice: ");
    }

    /**
     * Processes the choice of the user
     *
     * @param choice
     */
    private static void processChoice(int choice) {
        switch (choice) {
            case 1:
                borrowBook();
                break;
            case 2:
                returnBook();
                break;
            case 3:
                searchBook();
                break;
            case 4:
                library.displayTransactionHistory();
                break;
            case 5:
                System.out.println("Exiting...");
                System.exit(0);
                break;
            default:
                System.out.println("Invalid choice.");
        }
    }

    /**
     * Main method for the library
     *
     * @param args
     */
    public static void main(String[] args) { // main method
        /**
         * Initiallize library with the books and the members
         */
        library.addBook(new Book("Effective Java", "Joshua Bloch", "978-0134685991"));
        library.addBook(new Book("Clean Code", "Robert C. Martin", "978-0132350884"));
        library.addMember(new Member("Alice", "M001"));
        library.addMember(new Member("Bob", "M002"));

        while (true) {
            displayMainMenu();
            int choice = getChoice();
            processChoice(choice);
        }
    }

    /**
     * Gets user's choice
     *
     * @return user's choice
     */
    private static int getChoice() {
        int choice = 0;
        try {
            choice = scanner.nextInt();
            scanner.nextLine(); // Consume newline
        } catch (Exception e) {
            System.out.println("Invalid input. Please enter a number.");
            scanner.nextLine(); // Clear invalid input
        }
        return choice;
    }

    /**
     * Process of borrowing book
     */
    private static void borrowBook() {
        Member member = null;
        while (member == null) {
            System.out.print("Enter member ID: ");
            String memberId = scanner.nextLine();
            member = library.findMemberById(memberId);

            if (member == null) {
                System.out.println("Member not found. Please try again.");
            }
        }

        System.out.print("Enter book title or ISBN: ");
        String query = scanner.nextLine();
        Book book = library.searchBook(query);

        if (book != null && book.isAvailable()) {
            library.borrowBook(generateTransactionID(), new Date(), member, book);
            System.out.println("Book '" + book.getTitle() + "' borrowed by " + member.getName());
        } else {
            System.out.println("Book is not available.");
        }
    }

    /**
     * Process of returning book
     */
    private static void returnBook() {
        Member member = null;
        while (member == null) {
            System.out.print("Enter member ID: ");
            String memberId = scanner.nextLine();
            member = library.findMemberById(memberId);

            if (member == null) {
                System.out.println("Member not found. Please try again.");
            }
        }

        System.out.print("Enter book title or ISBN: ");
        String query = scanner.nextLine();
        Book book = library.searchBook(query);

        if (book != null && member.hasBorrowedBook(book)) {
            library.returnBook(generateTransactionID(), new Date(), member, book);
            System.out.println("Book '" + book.getTitle() + "' returned by " + member.getName());
        } else {
            System.out.println("Book was not borrowed by the member.");
        }
    }

    /**
     * Process of searching for book
     */
    private static void searchBook() {
        System.out.print("Enter book title or ISBN: ");
        String query = scanner.nextLine();
        Book book = library.searchBook(query);

        if (book != null) {
            System.out.printf("Book found: %s by %s\n", book.getTitle(), book.getAuthor());
        } else {
            System.out.println("Book not found.");
        }
    }

    /**
     * Generates transaction ID
     *
     * @return transaction ID
     */
    private static String generateTransactionID() {
        return "T" + System.currentTimeMillis();
    }
}

**Comment by abbiemn9** [comment]
package com.library.management;

import java.util.ArrayList;

/**
 * Library member who can borrow or return a book
 */
public class Member implements Borrowable {
    /**
     * member name
     */
    private String name;
    /**
     * Member ID
     */
    private String memberID;
    /**
     * List of books that member borrowed
     */
    private ArrayList<Book> borrowedBooks;

    /**
     * Constructing Member object with member name and member ID
     *
     * @param name
     * @param memberID
     */
    public Member(String name, String memberID) {
        this.name = name;
        this.memberID = memberID;
        this.borrowedBooks = new ArrayList<>();
    }

    /**
     * Gets name of member
     *
     * @return name of member
     */
    public String getName() {
        return name;
    }

    /**
     * Gets member ID
     *
     * @return member ID
     */
    public String getMemberID() {
        return memberID;
    }

    /**
     * Adds book to list that member has borrowed
     *
     * @param book borrowed
     */
    @Override
    public void borrowBook(Book book) {
        borrowedBooks.add(book);
    }

    /**
     * Removes book from list of books hat member has borrowed
     *
     * @param book returned
     */
    @Override
    public void returnBook(Book book) {
        borrowedBooks.remove(book);
    }

    /**
     * Sees if library member borrowed a certain book
     *
     * @param book
     * @return true if library member borrowed the book
     */
    public boolean hasBorrowedBook(Book book) {
        return borrowedBooks.contains(book);
    }

    /**
     * Returns String of member, with member name and member ID
     *
     * @return String of member
     */
    @Override
    public String toString() {
        return String.format("Name: %s, MemberID: %s", name, memberID);
    }
}

**Comment by abbiemn9** [comment]
package com.library.management;

import java.util.Date;

/**
 * A return transaction of a book from a library member
 */

public class ReturnTransaction extends Transaction {
    /**
     * Book is returned
     */
    private final Book book;
    /**
     * Member who returns the book
     */
    private final Member member;
    /**
     * Date of return
     */
    private final Date transactionDate;

    /**
     * Constructing a ReturnTransaction object with book and member
     *
     * @param book
     * @param member
     */
    public ReturnTransaction(Book book, Member member) {
        /**
         * Calls superclass constructor
         */
        super();
        this.book = book;
        this.member = member;
        this.transactionDate = new Date();
    }

    /** Gets the book return
     *
     * @return the book that is being returned
     */
    public Book getBook() {
        return book;
    }

    /**
     * Gets the member who is returning the book
     *
     * @return the member who is returning the book
     */
    public Member getMember() {
        return member;
    }

    /**
     * Gets date of the book return
     *
     * @return the date
     */
    public Date getTransactionDate() {
        return transactionDate;
    }

    /**
     * Processes the book return
     * Checks if the member has borrowed the book
     *
     */
    @Override
    public void process() {
        if (member.hasBorrowedBook(book)) {
            book.setAvailable(true);
            member.returnBook(book);
            System.out.println("Book returned successfully.");
        } else {
            System.out.println("This book was not borrowed by the member.");
        }
    }
}

**Comment by abbiemn9** [comment]
package com.library.management;

/**
 * Abstract Transaction in the library management system
 */
public abstract class Transaction {
    /**
     * Processes the transaction
     */
    public abstract void process();
}
