### ISSUE TITLE
Implement User Input Handling

### ISSUE THREAD

**Issue by as269** [as269/IS247Proj#9]
Use Scanner class:
Implement methods to get user input for adding books, members, borrowing, and returning books.

**Comment by abbiemn9** [comment]
public BookSearch {
    Scanner input = new Scanner(System.in);

        System.out.println("Enter name of book: ");
        this.bookName = input.nextLine();

System.out.println("Enter name of member: ");
        this.memberName = input.nextLine();

System.out.println("Enter name of book to borrow: ");
        this.borrow = input.nextLine();

System.out.println("Enter name of book to return: ");
        this.returning = input.nextLine();

    }
